### PR TITLE
updated version to 1.0.1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gongo** [comment]
Hi @gerar2-s09 

I'm sorry. I no longer maintain this library.
If you want to continue to maintain this, I will transfer ownership to you. How do you think?

**Comment by ghost** [comment]
Hi @gongo 

It's fine no problem, i think i can to maintain this for a time.

**Comment by gongo** [comment]
@gerar2-s09 

Thanks! 
I want to pass gem release privilege, so please send me (my email address) your email address.

**Comment by gongo** [comment]
I added @gerar2-s09 to https://rubygems.org/gems/angular-ui-calendar-rails onwer.
From now, mainstream of angular-ui-calendar-rails is https://github.com/gerar2-s09/angular-ui-calendar-rails .

Thanks!!

**Pull request closed without merging**
